spring.application.name=EmployeeManagementSystem

spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_db
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

jwt.secret=replace-this-with-a-long-random-secret-value-at-least-32-bytes
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update